### ISSUE TITLE
Long words overflow on mobile

### ISSUE THREAD

**Issue by katmh** [katavie/weirdflex#1]
![image](https://user-images.githubusercontent.com/4264038/76723827-0a240000-671f-11ea-9ab4-157161743095.png)

**Comment by JamsheedMistri** [comment]
Can confirm, am also getting this issue. Please fix, it's unusable until then.

**Comment by katmh** [comment]
- [Smaller font sizes on smaller screens](https://github.com/katavie/weirdflex/commit/7f24345e4b9375aed543c814326e72262a4c183c)
- [`word-wrap: break-word; word-break: break-word`](https://github.com/katavie/weirdflex/commit/cd39e38137fcd53e98b231a00f4980e3ca4e1e2e)
